import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { clone as cloneSkeleton } from 'three/examples/jsm/utils/SkeletonUtils.js';
import { getLeaderboard, leaderboardMode, submitScore, watchLeaderboard } from './leaderboard.js';

const GAME_SPEED=1.5,PLAYER_HEIGHT=1.7,IS_TOUCH=matchMedia('(pointer: coarse)').matches;

const scene = new THREE.Scene();
scene.background = new THREE.Color(0x02060b);
scene.fog = new THREE.FogExp2(0x02060b, 0.025);
const camera = new THREE.PerspectiveCamera(74, innerWidth / innerHeight, .05, 120);
camera.position.set(0, PLAYER_HEIGHT, 8);
const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio,IS_TOUCH?1.25:2)); renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap;
document.querySelector('#game').appendChild(renderer.domElement);

scene.add(new THREE.HemisphereLight(0x173d58, 0x050207, 1.5));
const cyan = new THREE.PointLight(0x00ddff, 35, 28); cyan.position.set(-8, 4, 2); scene.add(cyan);
const red = new THREE.PointLight(0xff174f, 30, 25); red.position.set(10, 3, -10); scene.add(red);
const floor = new THREE.Mesh(new THREE.PlaneGeometry(80,80,40,40), new THREE.MeshStandardMaterial({color:0x071219,roughness:.72,metalness:.45,wireframe:false}));
floor.rotation.x=-Math.PI/2; floor.receiveShadow=true; scene.add(floor);
const grid = new THREE.GridHelper(80,80,0x086879,0x0b2930); grid.position.y=.006; scene.add(grid);
const wallMat = new THREE.MeshStandardMaterial({color:0x8f999e,roughness:.82,metalness:.08});
const walls=[],wallMeshes=[];
function box(x,y,z,w,h,d){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),wallMat);m.position.set(x,y,z);m.castShadow=false;m.receiveShadow=true;scene.add(m);walls.push({x,z,w,d});wallMeshes.push(m);return m}
box(0,2,-40,80,4,1);box(0,2,40,80,4,1);box(-40,2,0,1,4,80);box(40,2,0,1,4,80);
for(const [x,z,w,d] of [[-12,-10,7,2],[11,-7,2,9],[-8,13,2,8],[14,14,8,2],[-25,20,7,2],[25,-22,2,8],[-23,-24,9,2],[25,5,6,2]]) box(x,1.5,z,w,3,d);

const gun=new THREE.Group();
const gunMat=new THREE.MeshStandardMaterial({color:0x17232b,metalness:.9,roughness:.25});
const accent=new THREE.MeshStandardMaterial({color:0x00ccdf,emissive:0x006673,emissiveIntensity:2});
const slide=new THREE.Mesh(new THREE.BoxGeometry(.22,.22,.72),gunMat); slide.position.set(.32,-.29,-.62); gun.add(slide);
const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.07,.07,.72,10),gunMat);barrel.rotation.x=Math.PI/2;barrel.position.set(.32,-.23,-.92);gun.add(barrel);
const stripe=new THREE.Mesh(new THREE.BoxGeometry(.225,.035,.35),accent);stripe.position.set(.32,-.17,-.61);gun.add(stripe);
const grip=new THREE.Mesh(new THREE.BoxGeometry(.19,.45,.22),gunMat);grip.rotation.x=-.15;grip.position.set(.32,-.5,-.48);gun.add(grip);camera.add(gun);scene.add(camera);
const muzzle=new THREE.PointLight(0xffb340,0,4);muzzle.position.set(.32,-.22,-1.3);camera.add(muzzle);
let weaponView=gun,weaponBasePosition=new THREE.Vector3(),weaponBaseRotationX=0;
// Lanterna acoplada à arma, apontando exatamente para o centro da mira.
const flashlight=new THREE.SpotLight(0xe7f7ff,95,38,THREE.MathUtils.degToRad(19),.48,1.35);
flashlight.position.set(.3,-.2,-.48);flashlight.castShadow=false;
const flashlightTarget=new THREE.Object3D();flashlightTarget.position.set(0,0,-12);camera.add(flashlight,flashlightTarget);flashlight.target=flashlightTarget;
const flameLight=new THREE.SpotLight(0xff5b12,0,10,THREE.MathUtils.degToRad(27),.65,1.6);flameLight.position.set(.3,-.22,-.7);flameLight.target=flashlightTarget;camera.add(flameLight);
const flameGeometry=new THREE.BufferGeometry(),flamePositions=new Float32Array(42*3);flameGeometry.setAttribute('position',new THREE.BufferAttribute(flamePositions,3));const flameParticles=new THREE.Points(flameGeometry,new THREE.PointsMaterial({color:0xff7a18,size:.24,transparent:true,opacity:.82,blending:THREE.AdditiveBlending,depthWrite:false,sizeAttenuation:true}));flameParticles.visible=false;camera.add(flameParticles);
const tracerGeometry=new THREE.CylinderGeometry(.012,.012,1,5),tracerMaterial=new THREE.MeshBasicMaterial({color:0x66f6ff,transparent:true,opacity:.9,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}),tracers=[];
for(let i=0;i<24;i++){const mesh=new THREE.Mesh(tracerGeometry,tracerMaterial.clone());mesh.visible=false;mesh.frustumCulled=false;mesh.userData.life=0;scene.add(mesh);tracers.push(mesh)}
// Uma única geometria/material compartilhados evitam alocações e compilação de shader no ataque do boss.
const bossOrbGeometry=new THREE.SphereGeometry(.2,8,6),bossOrbMaterial=new THREE.MeshBasicMaterial({color:0xff3b7f,transparent:true,opacity:.92,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});
const laserGeometryH=new THREE.BoxGeometry(78,.09,.42),laserGeometryV=new THREE.BoxGeometry(.42,.09,78),laserWarningMaterial=new THREE.MeshBasicMaterial({color:0xff284f,transparent:true,opacity:.22,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}),laserActiveMaterial=new THREE.MeshBasicMaterial({color:0xff123f,transparent:true,opacity:.92,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});

const keys={},mobileMove={x:0,z:0},enemies=[],enemyPool=[],allies=[],ammoCrates=[],powerUps=[],critPopups=[],bossOrbs=[],groundLasers=[],buffs={machinegun:0,flamethrower:0,speed:0,double:0,freeze:0},zombieAssets={};let cactusAsset=null,gargantuarAsset=null,preparedGargantuar=null,yaw=0,pitch=0,ammo=8,maxAmmo=8,kills=0,wave=1,waveKills=0,extraLives=0,active=false,paused=false,mouseDown=false,mobileRun=false,mobileJump=false,mouseSensitivity=1,gameSpeedMultiplier=1,grounded=true,jumpHeld=false,verticalVelocity=0,laserDamageCooldown=0,last=performance.now(),spawnTimer=0,ammoSpawnTimer=0,powerSpawnTimer=0,fireCooldown=0,flameCooldown=0,recoil=0,tracerCursor=0;
const E=document.querySelector('#enemies'),A=document.querySelector('#ammo'),K=document.querySelector('#kills'),R=document.querySelector('#record'),W=document.querySelector('#wave'),M=document.querySelector('#message'),L=document.querySelector('#lives'),B=document.querySelector('#buffs'),P=document.querySelector('#pause'),S=document.querySelector('#sensitivity'),SV=document.querySelector('#sensitivity-value'),GS=document.querySelector('#game-speed'),GSV=document.querySelector('#game-speed-value'),NICK=document.querySelector('#nickname'),RANKING=document.querySelector('#ranking'),RANKING_MODE=document.querySelector('#ranking-mode');
const minimapCanvas=document.querySelector('#minimap-canvas'),minimapCtx=minimapCanvas.getContext('2d');
let bestKills=Number(localStorage.getItem('neon-breach-record')||0),currentNickname=localStorage.getItem('neon-breach-nickname')||'';R.textContent=bestKills;NICK.value=currentNickname;RANKING_MODE.textContent=leaderboardMode==='online'?'RANKING GLOBAL · TEMPO REAL':'RANKING LOCAL · SUPABASE AGUARDANDO';
const escapeHTML=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
async function refreshRanking(){try{const rows=await getLeaderboard();RANKING.innerHTML=rows.length?rows.map(row=>`<li><b>${escapeHTML(row.nickname)}</b><span>ONDA ${row.wave}</span><strong>${row.kills} ABATES</strong></li>`).join(''):'<li class="ranking-empty">NENHUM REGISTRO AINDA</li>'}catch(error){console.error('Falha ao carregar ranking',error);RANKING.innerHTML='<li class="ranking-empty">RANKING INDISPONÍVEL</li>'}}
document.querySelector('#refresh-ranking').onclick=refreshRanking;refreshRanking();watchLeaderboard(refreshRanking);
const ray=new THREE.Raycaster();
const aimCenter=new THREE.Vector2(0,0),tmpDirection=new THREE.Vector3(),tmpToEnemy=new THREE.Vector3();
const tmpBossCore=new THREE.Vector3();
const tracerStart=new THREE.Vector3(),tracerEnd=new THREE.Vector3(),tracerMid=new THREE.Vector3(),tracerDirection=new THREE.Vector3(),upAxis=new THREE.Vector3(0,1,0);
const playerVelocity=new THREE.Vector3(),orbAimTarget=new THREE.Vector3();
function gaussianRandom(){const u=Math.max(Number.EPSILON,Math.random()),v=Math.max(Number.EPSILON,Math.random());return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
const startButton=document.querySelector('#start');
startButton.disabled=true; startButton.textContent='CARREGANDO ZUMBI...';
const modelLoader=new GLTFLoader();
const modelPath=file=>`${import.meta.env.BASE_URL}models/${file}`;
const ZOMBIE_TYPES={1:{tier:1,name:'BROWNCOAT',hp:2,speed:1.45,asset:'basic'},2:{tier:2,name:'BUCKET',hp:5,speed:1.18,asset:'bucket'},3:{tier:3,name:'FOOTBALL',hp:9,speed:1.82,asset:'football'}};
function chooseTier(){const r=Math.random(),football=wave>=5?Math.min(.28,.06+(wave-5)*.025):0,bucket=wave>=3?Math.min(.42,.16+(wave-3)*.025):0;return r<football?3:r<football+bucket?2:1}
function enemySpeed(config){return Math.min(4.2,config.speed*(1+Math.min(.55,(wave-1)*.035)))}
function preparePool(){const tiers=[1,1,1,1,1,1,1,1,2,2,2,2,2,3,3,3],schedule=globalThis.requestIdleCallback||((fn)=>setTimeout(fn,0));let prepared=0;function warm(){spawn(tiers[prepared]);const enemy=enemies.pop();scene.remove(enemy.mesh);enemyPool.push(enemy);E.textContent=0;prepared++;startButton.textContent=`PREPARANDO ZUMBIS ${prepared}/${tiers.length}`;if(prepared<tiers.length)schedule(warm);else{for(const e of enemyPool)scene.add(e.mesh);preparedGargantuar=cloneSkeleton(gargantuarAsset.scene);preparedGargantuar.position.y=-1000;preparedGargantuar.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=false;const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats)for(const key of ['map','normalMap','roughnessMap','metalnessMap','emissiveMap'])if(m?.[key])renderer.initTexture(m[key])}});scene.add(preparedGargantuar);const orbWarm=new THREE.Mesh(bossOrbGeometry,bossOrbMaterial);orbWarm.position.y=-1000;scene.add(orbWarm);renderer.compile(scene,camera);scene.remove(preparedGargantuar,orbWarm);preparedGargantuar.position.y=0;for(const e of enemyPool)scene.remove(e.mesh);startButton.disabled=false;startButton.textContent='ENTRAR NA ARENA'}}schedule(warm)}
Promise.all([
 modelLoader.loadAsync(modelPath('pvz-zombie-pbr.glb')),modelLoader.loadAsync(modelPath('zombie-bucket-pbr.glb')),modelLoader.loadAsync(modelPath('zombie-football-pbr.glb')),modelLoader.loadAsync(modelPath('cactus-pbr.glb')),modelLoader.loadAsync(modelPath('gargantuar-pbr.glb'))
]).then(([basic,bucket,football,cactus,gargantuar])=>{Object.assign(zombieAssets,{basic,bucket,football});cactusAsset=cactus;gargantuarAsset=gargantuar;preparePool()}).catch(err=>{console.error('Falha ao carregar personagens',err);startButton.disabled=false;startButton.textContent='ENTRAR NA ARENA'});
modelLoader.loadAsync(modelPath('ak47.glb')).then(g=>{const model=g.scene,bounds=new THREE.Box3().setFromObject(model),size=new THREE.Vector3(),center=new THREE.Vector3();bounds.getSize(size);const scale=1.22/Math.max(size.x,size.y,size.z);model.scale.setScalar(scale);new THREE.Box3().setFromObject(model).getCenter(center);model.position.sub(center);model.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=false}});const pivot=new THREE.Group();pivot.position.set(.35,-.34,-.72);if(size.x>size.z)pivot.rotation.y=-Math.PI/2;else pivot.rotation.y=Math.PI;pivot.rotation.x=-.035;pivot.add(model);camera.add(pivot);weaponView=pivot;weaponBasePosition=pivot.position.clone();weaponBaseRotationX=pivot.rotation.x;gun.visible=false}).catch(err=>console.warn('AK indisponível; mantendo pistola.',err));
function blocked(x,z,r=.38){if(Math.abs(x)>39-r||Math.abs(z)>39-r)return true;return walls.slice(4).some(o=>Math.abs(x-o.x)<o.w/2+r&&Math.abs(z-o.z)<o.d/2+r)}
function randomFreeSpot(){let x,z,tries=0;do{x=THREE.MathUtils.randFloat(-36,36);z=THREE.MathUtils.randFloat(-36,36);tries++}while((blocked(x,z,.9)||Math.hypot(x-camera.position.x,z-camera.position.z)<5)&&tries<100);return{x,z}}
function spawnAmmoCrate(){const{x,z}=randomFreeSpot();
 const crate=new THREE.Group(),shell=new THREE.Mesh(new THREE.BoxGeometry(.9,.65,.75),new THREE.MeshStandardMaterial({color:0x164b55,emissive:0x003a42,emissiveIntensity:1.5,metalness:.55,roughness:.3}));shell.castShadow=true;crate.add(shell);
 const crossMat=new THREE.MeshBasicMaterial({color:0x85f9ff,toneMapped:false});const barV=new THREE.Mesh(new THREE.BoxGeometry(.16,.42,.77),crossMat),barH=new THREE.Mesh(new THREE.BoxGeometry(.48,.16,.77),crossMat);crate.add(barV,barH);
 const glow=new THREE.PointLight(0x00eaff,12,4,1.7);glow.position.y=.35;crate.add(glow);crate.position.set(x,.48,z);scene.add(crate);ammoCrates.push({mesh:crate,phase:Math.random()*6.28});
}
const POWER_TYPES=[
 {id:'machinegun',name:'METRALHADORA',color:0xffd52e,duration:10},
 {id:'flamethrower',name:'LANÇA-CHAMAS',color:0xff4a18,duration:9},
 {id:'speed',name:'VELOCIDADE',color:0x36f4ff,duration:12},
 {id:'life',name:'VIDA EXTRA',color:0xff55b8},
 {id:'magazine',name:'PENTE +2',color:0x9d6cff},
 {id:'double',name:'DANO DUPLO',color:0xff304f,duration:12},
 {id:'freeze',name:'TEMPO LENTO',color:0x65a7ff,duration:9},
 {id:'cactus',name:'CACTUS ALIADO',color:0x63ff4d}
];
function choosePowerType(){const available=POWER_TYPES.filter(p=>!(isBossWave()&&p.id==='machinegun')),total=available.reduce((sum,p)=>sum+(p.id==='life' ? .5 : 1),0);let roll=Math.random()*total;for(const type of available){roll-=type.id==='life' ? .5 : 1;if(roll<=0)return type}return available[0]}
function spawnPowerUp(){const type=choosePowerType(),{x,z}=randomFreeSpot(),mesh=new THREE.Group();const core=new THREE.Mesh(new THREE.OctahedronGeometry(.55),new THREE.MeshStandardMaterial({color:type.color,emissive:type.color,emissiveIntensity:2.6,metalness:.35,roughness:.2}));const ring=new THREE.Mesh(new THREE.TorusGeometry(.78,.055,8,24),new THREE.MeshBasicMaterial({color:type.color,toneMapped:false}));ring.rotation.x=Math.PI/2;mesh.add(core,ring);const light=new THREE.PointLight(type.color,16,5,1.7);mesh.add(light);mesh.position.set(x,.9,z);scene.add(mesh);powerUps.push({mesh,type,phase:Math.random()*6.28})}
function spawnCactus(position){if(!cactusAsset)return;const visual=cloneSkeleton(cactusAsset.scene),bounds=new THREE.Box3().setFromObject(visual),size=new THREE.Vector3(),center=new THREE.Vector3();bounds.getSize(size);visual.scale.setScalar(2.25/size.y);const scaled=new THREE.Box3().setFromObject(visual);scaled.getCenter(center);visual.position.set(-center.x,-scaled.min.y,-center.z);visual.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=true}});const mesh=new THREE.Group();mesh.add(visual);mesh.position.set(position.x,0,position.z);scene.add(mesh);allies.push({mesh,shots:50,cooldown:.35,phase:Math.random()*6.28})}
function collectPower(type,position){if(type.id==='life'){extraLives++;L.textContent=extraLives}else if(type.id==='magazine'){maxAmmo+=2;ammo=Math.min(maxAmmo,ammo+2);updateAmmo()}else if(type.id==='cactus')spawnCactus(position);else{buffs[type.id]=type.duration}flash(`${type.name} ATIVADO${type.duration?`  //  ${type.duration}s`:type.id==='cactus'?'  //  50 TIROS':''}`);renderBuffs()}
function updateAmmo(){const infinite=isBossWave()||buffs.machinegun>0;A.textContent=infinite?'∞':ammo;A.nextElementSibling.textContent=`/ ${maxAmmo}`;A.parentElement.classList.toggle('empty',ammo===0&&!infinite)}
let lastBuffHTML='';
function renderBuffs(){const names={machinegun:'METRALHADORA',flamethrower:'LANÇA-CHAMAS',speed:'VELOCIDADE',double:'DANO DUPLO',freeze:'TEMPO LENTO'},html=Object.entries(buffs).filter(([,v])=>v>0).map(([k,v])=>`<div class="buff">${names[k]} <b>${Math.ceil(v)}s</b></div>`).join('');if(html!==lastBuffHTML){B.innerHTML=html;lastBuffHTML=html}}
function createHealthBar(){const group=new THREE.Group(),back=new THREE.Mesh(new THREE.PlaneGeometry(1.38,.18),new THREE.MeshBasicMaterial({color:0x160208,transparent:true,opacity:.88,depthTest:false})),fill=new THREE.Mesh(new THREE.PlaneGeometry(1.24,.1),new THREE.MeshBasicMaterial({color:0x39ff72,depthTest:false,toneMapped:false}));back.renderOrder=20;fill.position.z=.006;fill.renderOrder=21;group.position.set(0,2.8,.05);group.add(back,fill);group.traverse(o=>o.userData.ignoreRay=true);return{group,fill}}
function updateHealth(enemy){const ratio=Math.max(0,enemy.hp/enemy.maxHp);enemy.healthFill.scale.x=ratio;enemy.healthFill.position.x=-(1-ratio)*.62;enemy.healthFill.material.color.setHex(ratio>.55?0x39ff72:ratio>.25?0xffd52e:0xff304f)}
function showCrit(position){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=128;const ctx=canvas.getContext('2d');ctx.font='900 72px Rajdhani, sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=12;ctx.strokeStyle='#4b0010';ctx.strokeText('CRIT!',128,64);ctx.fillStyle='#ffdf35';ctx.fillText('CRIT!',128,64);const texture=new THREE.CanvasTexture(canvas),material=new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false,toneMapped:false}),sprite=new THREE.Sprite(material);sprite.position.copy(position);sprite.position.y+=.28;sprite.scale.set(1.35,.68,1);sprite.renderOrder=30;sprite.userData.ignoreRay=true;scene.add(sprite);critPopups.push({sprite,life:.85})}
function spawn(forcedTier=chooseTier()){let x,z;do{const a=Math.random()*Math.PI*2,d=15+Math.random()*7;x=camera.position.x+Math.cos(a)*d;z=camera.position.z+Math.sin(a)*d}while(blocked(x,z,1));
 const config=ZOMBIE_TYPES[forcedTier],poolIndex=enemyPool.findIndex(e=>e.tier===forcedTier),pooled=poolIndex>=0?enemyPool.splice(poolIndex,1)[0]:null;if(pooled){pooled.mesh.position.set(x,pooled.spawnY,z);pooled.hp=pooled.maxHp=config.hp;pooled.speed=enemySpeed(config);pooled.step=Math.random()*Math.PI*2;updateHealth(pooled);scene.add(pooled.mesh);enemies.push(pooled);E.textContent=enemies.length;return}
 let mesh,mixer=null,visual=null;
 const asset=zombieAssets[config.asset];if(asset){visual=cloneSkeleton(asset.scene);const bounds=new THREE.Box3().setFromObject(visual),size=new THREE.Vector3();bounds.getSize(size);visual.scale.setScalar(2.5/size.y);const scaled=new THREE.Box3().setFromObject(visual),center=new THREE.Vector3();scaled.getCenter(center);visual.position.set(-center.x,-scaled.min.y,-center.z);visual.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=true;const wasArray=Array.isArray(o.material),mats=wasArray?o.material:[o.material],copies=mats.map(m=>{const copy=m.clone();if(copy.name.includes('EYES')){copy.emissive?.set(forcedTier===3?0xff392e:0x63ff3e);copy.emissiveMap=copy.map;copy.emissiveIntensity=4.5;copy.toneMapped=false}return copy});o.material=wasArray?copies:copies[0]}});mesh=new THREE.Group();mesh.add(visual);if(asset.animations.length){mixer=new THREE.AnimationMixer(visual);const clip=asset.animations.find(a=>a.name==='zombie_shuffle')||asset.animations[0];mixer.clipAction(clip).play();}}
 else{const mat=new THREE.MeshStandardMaterial({color:0x9d0a2f,emissive:0x580017,emissiveIntensity:1.3,roughness:.45});mesh=new THREE.Mesh(new THREE.BoxGeometry(1.05,2.5,1.05),mat);mesh.position.y=1.25;mesh.castShadow=true;}
 const health=createHealthBar();mesh.add(health.group);mesh.position.x=x;mesh.position.z=z;scene.add(mesh);const enemy={mesh,mixer,visual,visualBaseY:visual?.position.y||0,spawnY:mesh.position.y,tier:forcedTier,type:config.name,speed:enemySpeed(config),hp:config.hp,maxHp:config.hp,healthFill:health.fill,step:Math.random()*Math.PI*2,isBoss:false};mesh.traverse(o=>{if(!o.userData.ignoreRay)o.userData.enemy=enemy});updateHealth(enemy);enemies.push(enemy);E.textContent=enemies.length;
}
function isBossWave(){return wave===2||wave%10===0}
function clearBossOrbs(){for(const orb of bossOrbs)scene.remove(orb.mesh);bossOrbs.length=0}
function clearGroundLasers(){for(const laser of groundLasers)scene.remove(laser.mesh);groundLasers.length=0}
function spawnLaserPattern(){const count=3+Math.floor(Math.random()*2);for(let i=0;i<count;i++){const vertical=Math.random()<.5,start=Math.random()<.5?-38:38,end=-start,mesh=new THREE.Mesh(vertical?laserGeometryV:laserGeometryH,laserWarningMaterial);mesh.position.set(vertical?start:0,.075,vertical?0:start);mesh.visible=i===0;mesh.renderOrder=8;scene.add(mesh);groundLasers.push({mesh,vertical,lane:start,start,end,age:-i*.42,active:false,hit:false})}flash(`${count} VARREDURAS DETECTADAS  //  PULE!`)}
function spawnLaserBoss(){const{x,z}=randomFreeSpot(),mesh=new THREE.Group(),armor=new THREE.MeshStandardMaterial({color:0x260713,emissive:0xa00028,emissiveIntensity:2.3,metalness:.72,roughness:.23}),dark=new THREE.MeshStandardMaterial({color:0x090c12,metalness:.9,roughness:.2});const body=new THREE.Mesh(new THREE.CylinderGeometry(.82,1.05,2.5,8),armor),head=new THREE.Mesh(new THREE.OctahedronGeometry(.72),armor),ring=new THREE.Mesh(new THREE.TorusGeometry(1.05,.11,8,28),dark);body.position.y=1.65;head.position.y=3.25;ring.position.y=2.1;ring.rotation.x=Math.PI/2;mesh.add(body,head,ring);for(const side of [-1,1]){const leg=new THREE.Mesh(new THREE.BoxGeometry(.42,1.4,.52),dark);leg.position.set(side*.52,.7,0);mesh.add(leg)}const health=createHealthBar();health.group.position.y=4.25;health.group.scale.set(1.7,1.2,1);mesh.add(health.group);mesh.position.set(x,0,z);const boss={mesh,visual:null,mixer:null,spawnY:0,tier:4,type:'LASER WARDEN',speed:.78,hp:400,maxHp:400,healthFill:health.fill,step:0,isBoss:true,laserBoss:true,attackCooldown:2.3};mesh.traverse(o=>{if(o.isMesh&&!o.userData.ignoreRay)o.userData.enemy=boss});scene.add(mesh);updateHealth(boss);enemies.push(boss);E.textContent=enemies.length;flash('LASER WARDEN  //  400 DE VIDA')}
function spawnBossOrbs(boss){
 const origin=new THREE.Vector3();boss.core.getWorldPosition(origin);
 for(let i=0;i<15;i++){const angle=i/15*Math.PI*2,mesh=new THREE.Mesh(bossOrbGeometry,bossOrbMaterial),orb={mesh,velocity:new THREE.Vector3(),life:30,angle,launched:false,boss,spread:gaussianRandom()*.105,lead:.12+Math.random()*.72,curve:gaussianRandom()*.16};mesh.position.copy(origin);mesh.userData.bossOrb=orb;scene.add(mesh);bossOrbs.push(orb)}
 boss.core.visible=false;boss.charging=false;boss.chargeTimer=0;boss.volleyActive=true;boss.volleyTimer=.3;boss.volleyLeft=15;flash('15 ORBES INVOCADOS  //  RAJADA EM 0.3s')
}
function launchBossOrb(orb){orb.launched=true;orb.life=6;orbAimTarget.set(camera.position.x,PLAYER_HEIGHT*.72,camera.position.z).addScaledVector(playerVelocity,orb.lead);orb.velocity.copy(orbAimTarget).sub(orb.mesh.position).normalize().applyAxisAngle(upAxis,orb.spread).multiplyScalar(10.5)}
function updateLaserBoss(boss,dt){boss.attackCooldown-=dt;boss.mesh.children[2].rotation.z+=dt*1.8;if(boss.attackCooldown<=0){spawnLaserPattern();boss.attackCooldown=9.8+Math.random()*1.2}}
function spawnBoss(){
 if(wave===2){spawnLaserBoss();return}
 if(!gargantuarAsset){flash('GARGANTUAR INDISPONÍVEL');return}
 const {x,z}=randomFreeSpot(),visual=preparedGargantuar||cloneSkeleton(gargantuarAsset.scene),bounds=new THREE.Box3().setFromObject(visual),size=new THREE.Vector3(),center=new THREE.Vector3();preparedGargantuar=null;bounds.getSize(size);visual.scale.setScalar(4.8/size.y);const scaled=new THREE.Box3().setFromObject(visual);scaled.getCenter(center);visual.position.set(-center.x,-scaled.min.y,-center.z);
 visual.traverse(o=>{if(o.isMesh){o.castShadow=false;o.receiveShadow=true;const eye=(o.name+' '+(o.material?.name||'')).toUpperCase().includes('EYES'),wasArray=Array.isArray(o.material),mats=wasArray?o.material:[o.material];o.material=mats.map(m=>{const copy=m.clone();if(eye){copy.emissive?.set(0xff174f);copy.emissiveMap=copy.map;copy.emissiveIntensity=6;copy.toneMapped=false}return copy});if(!wasArray)o.material=o.material[0]}});
 const mesh=new THREE.Group();mesh.add(visual);mesh.position.set(x,0,z);const health=createHealthBar();health.group.position.y=5.15;health.group.scale.set(2.25,1.35,1);mesh.add(health.group);
 const core=new THREE.Group(),coreBall=new THREE.Mesh(new THREE.SphereGeometry(.32,14,10),new THREE.MeshBasicMaterial({color:0xff2b79,transparent:true,opacity:.8,toneMapped:false})),coreLight=new THREE.PointLight(0xff174f,45,8,1.5);core.add(coreBall,coreLight);core.position.set(0,2.75,.62);core.visible=false;mesh.add(core);scene.add(mesh);
 let mixer=null;if(gargantuarAsset.animations.length){mixer=new THREE.AnimationMixer(visual);mixer.clipAction(gargantuarAsset.animations[0]).play()}
 const bossNumber=wave/10,maxHp=Math.round(500*Math.pow(1.7,bossNumber-1)),boss={mesh,visual,mixer,visualBaseY:visual.position.y,spawnY:0,tier:4,type:'GARGANTUAR',speed:Math.min(2.25,1.05+(bossNumber-1)*.12),hp:maxHp,maxHp,healthFill:health.fill,step:0,isBoss:true,core,coreBall,charging:false,chargeTimer:0,attackCooldown:4.5,volleyActive:false,volleyTimer:0,volleyLeft:0};mesh.traverse(o=>{if(!o.userData.ignoreRay&&!o.userData.bossOrb)o.userData.enemy=boss});updateHealth(boss);enemies.push(boss);E.textContent=enemies.length;flash(`BOSS GARGANTUAR  //  ${maxHp} DE VIDA`)
}
function clearRegularEnemies(){for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(!e.isBoss){scene.remove(e.mesh);enemies.splice(i,1);enemyPool.push(e)}}E.textContent=enemies.length}
function clearAmmoCrates(){for(const crate of ammoCrates)scene.remove(crate.mesh);ammoCrates.length=0}
function advanceWave(){wave++;waveKills=0;W.textContent=`ONDA ${String(wave).padStart(2,'0')}`;if(isBossWave()){clearRegularEnemies();clearBossOrbs();clearAmmoCrates();flash(`ONDA ${wave}  //  METRALHADORA ILIMITADA`);spawnBoss()}else{flash(`ONDA ${wave}  //  NOVA COMPOSIÇÃO`);for(let i=0;i<2;i++)spawn()}updateAmmo()}
function reset(){enemies.forEach(e=>{scene.remove(e.mesh);if(!e.isBoss)enemyPool.push(e)});clearBossOrbs();clearGroundLasers();allies.forEach(a=>scene.remove(a.mesh));ammoCrates.forEach(c=>scene.remove(c.mesh));powerUps.forEach(p=>scene.remove(p.mesh));critPopups.forEach(p=>{scene.remove(p.sprite);p.sprite.material.map.dispose();p.sprite.material.dispose()});enemies.length=allies.length=ammoCrates.length=powerUps.length=critPopups.length=0;camera.position.set(0,PLAYER_HEIGHT,8);yaw=pitch=verticalVelocity=0;mobileMove.x=mobileMove.z=0;mobileRun=mobileJump=false;grounded=true;jumpHeld=false;ammo=maxAmmo=8;kills=0;wave=1;waveKills=0;extraLives=0;laserDamageCooldown=0;spawnTimer=ammoSpawnTimer=powerSpawnTimer=0;Object.keys(buffs).forEach(k=>buffs[k]=0);active=true;paused=false;P.classList.remove('visible');L.textContent=0;K.textContent=0;W.textContent='ONDA 01';renderBuffs();updateAmmo();document.body.classList.add('playing');for(let i=0;i<4;i++)spawn();for(let i=0;i<2;i++)spawnAmmoCrate();spawnPowerUp();if(!IS_TOUCH)renderer.domElement.requestPointerLock()}
function belongsTo(object,parent){for(let o=object;o;o=o.parent)if(o===parent)return true;return false}
function spawnTracerBetween(start,end,color=0x66f6ff){const tracer=tracers[tracerCursor++%tracers.length];tracerStart.copy(start);tracerEnd.copy(end);tracerDirection.subVectors(tracerEnd,tracerStart);const length=tracerDirection.length();tracer.position.copy(tracerMid.addVectors(tracerStart,tracerEnd).multiplyScalar(.5));tracer.scale.set(1,length,1);tracer.quaternion.setFromUnitVectors(upAxis,tracerDirection.normalize());tracer.material.color.setHex(color);tracer.material.opacity=.95;tracer.userData.life=.13;tracer.visible=true}
function spawnTracer(end){muzzle.getWorldPosition(tracerStart);spawnTracerBetween(tracerStart,end)}
function damageEnemy(hit,damage=1){if(!hit||!enemies.includes(hit))return;hit.hp-=damage;updateHealth(hit);if(hit.hp>0){flash(`${hit.type}  //  ${Math.ceil(hit.hp)}/${hit.maxHp} VIDA`);return}const idx=enemies.indexOf(hit);scene.remove(hit.mesh);enemies.splice(idx,1);if(!hit.isBoss)enemyPool.push(hit);else{clearBossOrbs();clearGroundLasers()}kills++;if(kills>bestKills){bestKills=kills;R.textContent=bestKills;localStorage.setItem('neon-breach-record',String(bestKills))}ammo=Math.min(maxAmmo,ammo+1);K.textContent=kills;flash(`${hit.isBoss?'BOSS':'TIER '+hit.tier} ELIMINADO  //  +1 BALA`);E.textContent=enemies.length;if(hit.isBoss)advanceWave();else if(++waveKills>=6)advanceWave();updateAmmo()}
function shoot(){if(!active||(!IS_TOUCH&&document.pointerLockElement!==renderer.domElement)||buffs.flamethrower>0)return;const infinite=isBossWave()||buffs.machinegun>0;if(!infinite&&ammo<=0){flash('SEM MUNIÇÃO — PROCURE UMA CAIXA');return}if(!infinite)ammo--;updateAmmo();recoil=infinite ? .07 : .12;muzzle.intensity=18;setTimeout(()=>muzzle.intensity=0,45);
 ray.setFromCamera(aimCenter,camera);ray.far=80;
 // Limita o teste às paredes e aos inimigos, evitando percorrer toda a cena a cada tiro.
 const hits=ray.intersectObjects(wallMeshes.concat(enemies.map(e=>e.mesh),bossOrbs.map(o=>o.mesh)),true).filter(h=>h.object.isMesh&&!h.object.userData.ignoreRay);
 const surface=hits[0],orb=surface?.object.userData.bossOrb,hit=surface?.object.userData.enemy;
 spawnTracer(surface?.point||ray.ray.at(80,tracerEnd));
 if(orb){const i=bossOrbs.indexOf(orb);if(i>=0){scene.remove(orb.mesh);bossOrbs.splice(i,1);flash(`ORBE DESTRUÍDO  //  RESTAM ${bossOrbs.length}`)}}else if(hit){const localImpact=hit.mesh.worldToLocal(surface.point.clone()),headshot=localImpact.y>(hit.isBoss?3.55:1.82);if(headshot)showCrit(surface.point);damageEnemy(hit,(buffs.double>0?2:1)*(headshot?2:1))}}
function flash(t){M.textContent=t;M.style.opacity=1;clearTimeout(M.t);M.t=setTimeout(()=>M.style.opacity=0,1000)}
function setPaused(value){if(!active)return;paused=value;mouseDown=false;P.classList.toggle('visible',paused);if(paused){if(!IS_TOUCH)document.exitPointerLock();flameLight.intensity=0;flameParticles.visible=false}else if(!IS_TOUCH)renderer.domElement.requestPointerLock()}
function gameOver(){active=false;paused=false;P.classList.remove('visible');mouseDown=false;flameLight.intensity=0;flameParticles.visible=false;document.exitPointerLock();document.body.classList.remove('playing');const s=document.querySelector('#screen');s.classList.add('visible');s.querySelector('.eyebrow').textContent='SINAL VITAL PERDIDO';s.querySelector('h1').innerHTML=`${kills} <em>ABATES</em>`;s.querySelector('p').innerHTML=`${escapeHTML(currentNickname)}, você chegou à onda <b>${wave}</b>.<br>Os invasores romperam sua defesa.`;document.querySelector('#start').textContent='TENTAR NOVAMENTE';submitScore(currentNickname,kills,wave).then(refreshRanking).catch(error=>{console.error('Falha ao enviar pontuação',error);refreshRanking()});const d=document.querySelector('#damage');d.style.opacity=1;setTimeout(()=>d.style.opacity=0,500)}
function playerHit(sourceEnemy=null){if(extraLives>0){extraLives--;L.textContent=extraLives;if(sourceEnemy&&!sourceEnemy.isBoss){const i=enemies.indexOf(sourceEnemy);if(i>=0){scene.remove(sourceEnemy.mesh);enemies.splice(i,1);enemyPool.push(sourceEnemy)}}flash('VIDA EXTRA CONSUMIDA');const d=document.querySelector('#damage');d.style.opacity=.75;setTimeout(()=>d.style.opacity=0,250);return true}gameOver();return false}
startButton.onclick=()=>{const nickname=NICK.value.trim().replace(/[^\p{L}\p{N}_ -]/gu,'').slice(0,16);if(!nickname){NICK.setCustomValidity('Escolha um nickname para entrar na arena.');NICK.reportValidity();NICK.focus();return}NICK.setCustomValidity('');NICK.value=currentNickname=nickname;localStorage.setItem('neon-breach-nickname',nickname);reset()};NICK.addEventListener('input',()=>NICK.setCustomValidity(''));document.querySelector('#resume').onclick=()=>setPaused(false);S.oninput=()=>{mouseSensitivity=Number(S.value);SV.textContent=`${mouseSensitivity.toFixed(2)}×`};GS.oninput=()=>{gameSpeedMultiplier=Number(GS.value);GSV.textContent=`${gameSpeedMultiplier.toFixed(1)}×`};addEventListener('keydown',e=>{if(e.code==='KeyP'&&active&&!e.repeat){e.preventDefault();setPaused(!paused);return}keys[e.code]=true;if(e.code==='Space')e.preventDefault()});addEventListener('keyup',e=>{keys[e.code]=false;if(e.code==='Space')jumpHeld=false});addEventListener('mousedown',()=>{if(paused)return;mouseDown=true;shoot()});addEventListener('mouseup',()=>mouseDown=false);
if(IS_TOUCH){
 const stick=document.querySelector('#move-stick'),knob=document.querySelector('#stick-knob'),look=document.querySelector('#mobile-look-zone'),fire=document.querySelector('#mobile-fire'),jump=document.querySelector('#mobile-jump'),run=document.querySelector('#mobile-run');let stickId=null,lookId=null,lastLookX=0,lastLookY=0;
 const moveStick=e=>{const rect=stick.querySelector('.stick-ring').getBoundingClientRect(),dx=e.clientX-(rect.left+rect.width/2),dy=e.clientY-(rect.top+rect.height/2),distance=Math.hypot(dx,dy),limit=46,scale=distance>limit?limit/distance:1,x=dx*scale,y=dy*scale;knob.style.transform=`translate(${x}px,${y}px)`;mobileMove.x=x/limit;mobileMove.z=y/limit};
 stick.onpointerdown=e=>{stickId=e.pointerId;stick.setPointerCapture(e.pointerId);moveStick(e)};stick.onpointermove=e=>{if(e.pointerId===stickId)moveStick(e)};const releaseStick=e=>{if(e.pointerId!==stickId)return;stickId=null;mobileMove.x=mobileMove.z=0;knob.style.transform='translate(0,0)'};stick.onpointerup=stick.onpointercancel=releaseStick;
 look.onpointerdown=e=>{lookId=e.pointerId;lastLookX=e.clientX;lastLookY=e.clientY;look.setPointerCapture(e.pointerId)};look.onpointermove=e=>{if(e.pointerId!==lookId||paused)return;const dx=e.clientX-lastLookX,dy=e.clientY-lastLookY;lastLookX=e.clientX;lastLookY=e.clientY;yaw-=dx*.0052*mouseSensitivity;pitch-=dy*.0045*mouseSensitivity;pitch=Math.max(-1.35,Math.min(1.35,pitch))};look.onpointerup=look.onpointercancel=e=>{if(e.pointerId===lookId)lookId=null};
 const hold=(button,onDown,onUp)=>{button.onpointerdown=e=>{e.preventDefault();button.setPointerCapture(e.pointerId);button.classList.add('pressed');onDown()};button.onpointerup=button.onpointercancel=e=>{button.classList.remove('pressed');onUp()}};
 hold(fire,()=>{if(!paused){mouseDown=true;shoot()}},()=>mouseDown=false);hold(jump,()=>mobileJump=true,()=>mobileJump=false);hold(run,()=>mobileRun=true,()=>mobileRun=false);document.querySelector('#mobile-pause').onclick=()=>setPaused(!paused);
}
addEventListener('mousemove',e=>{if(active&&!paused&&document.pointerLockElement===renderer.domElement){yaw-=e.movementX*.0022*mouseSensitivity;pitch-=e.movementY*.0022*mouseSensitivity;pitch=Math.max(-1.35,Math.min(1.35,pitch))}});
renderer.domElement.onclick=()=>{if(!IS_TOUCH&&active&&document.pointerLockElement!==renderer.domElement)renderer.domElement.requestPointerLock()};
function update(dt,t){camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch;for(const k of Object.keys(buffs))if(buffs[k]>0){buffs[k]=Math.max(0,buffs[k]-dt);if(buffs[k]===0){flash(`${k.toUpperCase()} ENCERRADO`);updateAmmo()}}renderBuffs();fireCooldown-=dt;flameCooldown-=dt;laserDamageCooldown=Math.max(0,laserDamageCooldown-dt);if(mouseDown&&(isBossWave()||buffs.machinegun>0)&&fireCooldown<=0){fireCooldown=.085;shoot()}
 flameLight.intensity=mouseDown&&buffs.flamethrower>0?85:0;flameParticles.visible=mouseDown&&buffs.flamethrower>0;if(flameParticles.visible){for(let i=0;i<42;i++){const age=((t*.0017+i/42)%1),spread=age*1.75;flamePositions[i*3]=.3+(Math.sin(i*12.7+t*.015)*spread);flamePositions[i*3+1]=-.22+(Math.cos(i*8.3+t*.012)*spread*.55);flamePositions[i*3+2]=-.8-age*8}flameGeometry.attributes.position.needsUpdate=true}if(mouseDown&&buffs.flamethrower>0&&flameCooldown<=0){flameCooldown=.18;recoil=.035;camera.getWorldDirection(tmpDirection);for(const e of [...enemies]){tmpToEnemy.copy(e.mesh.position).sub(camera.position);const dist=tmpToEnemy.length();if(dist<9&&tmpToEnemy.normalize().dot(tmpDirection)>.88)damageEnemy(e,buffs.double>0?2:1)}}
 if((keys.Space||mobileJump)&&grounded&&!jumpHeld){verticalVelocity=7.6;grounded=false;jumpHeld=true}if(!keys.Space&&!mobileJump)jumpHeld=false;if(!grounded){verticalVelocity-=15.5*dt;camera.position.y+=verticalVelocity*dt;if(camera.position.y<=PLAYER_HEIGHT){camera.position.y=PLAYER_HEIGHT;verticalVelocity=0;grounded=true}}
 const speed=((keys.ShiftLeft||mobileRun)?7.2:4.5)*(buffs.speed>0?1.65:1)*dt;let dx=mobileMove.x,dz=mobileMove.z;if(keys.KeyW)dz-=1;if(keys.KeyS)dz+=1;if(keys.KeyA)dx-=1;if(keys.KeyD)dx+=1;if(dx||dz){const l=Math.max(1,Math.hypot(dx,dz));dx/=l;dz/=l;const sx=(dx*Math.cos(yaw)+dz*Math.sin(yaw))*speed,sz=(-dx*Math.sin(yaw)+dz*Math.cos(yaw))*speed;playerVelocity.lerp(tmpDirection.set(sx/Math.max(dt,.001),0,sz/Math.max(dt,.001)),Math.min(1,dt*9));if(!blocked(camera.position.x+sx,camera.position.z))camera.position.x+=sx;if(!blocked(camera.position.x,camera.position.z+sz))camera.position.z+=sz;weaponView.position.y=weaponBasePosition.y+Math.sin(t*.012)*.008;weaponView.position.x=weaponBasePosition.x+Math.cos(t*.006)*.006}else{playerVelocity.multiplyScalar(Math.pow(.02,dt));weaponView.position.copy(weaponBasePosition)}recoil*=Math.pow(.001,dt);weaponView.rotation.x=weaponBaseRotationX+recoil;
 spawnTimer+=dt;if(!isBossWave()&&spawnTimer>Math.max(1.5,4-wave*.2)){spawnTimer=0;if(enemies.length<Math.min(16,5+wave))spawn()}
 if(!isBossWave()){ammoSpawnTimer+=dt;if(ammoSpawnTimer>12&&ammoCrates.length<3){ammoSpawnTimer=0;spawnAmmoCrate()}}
 powerSpawnTimer+=dt;if(powerSpawnTimer>Math.max(9,18-wave*.3)&&powerUps.length<4){powerSpawnTimer=0;spawnPowerUp()}
 for(let i=ammoCrates.length-1;i>=0;i--){const c=ammoCrates[i];c.mesh.rotation.y+=dt*.9;c.mesh.position.y=.48+Math.sin(t*.002+c.phase)*.08;if(Math.hypot(c.mesh.position.x-camera.position.x,c.mesh.position.z-camera.position.z)<1.15&&ammo<maxAmmo){ammo=Math.min(maxAmmo,ammo+3);updateAmmo();flash('CAIXA COLETADA  //  +3 BALAS');scene.remove(c.mesh);ammoCrates.splice(i,1)}}
 for(let i=powerUps.length-1;i>=0;i--){const p=powerUps[i];p.mesh.rotation.y+=dt*1.4;p.mesh.children[1].rotation.z+=dt;p.mesh.position.y=.9+Math.sin(t*.002+p.phase)*.12;if(Math.hypot(p.mesh.position.x-camera.position.x,p.mesh.position.z-camera.position.z)<1.25){collectPower(p.type,p.mesh.position);scene.remove(p.mesh);powerUps.splice(i,1)}}
 for(let i=critPopups.length-1;i>=0;i--){const p=critPopups[i];p.life-=dt;p.sprite.position.y+=dt*.75;p.sprite.material.opacity=Math.max(0,p.life/.85);p.sprite.scale.multiplyScalar(1+dt*.35);if(p.life<=0){scene.remove(p.sprite);p.sprite.material.map.dispose();p.sprite.material.dispose();critPopups.splice(i,1)}}
 for(const tracer of tracers)if(tracer.visible){tracer.userData.life-=dt;tracer.material.opacity=Math.max(0,tracer.userData.life/.13);if(tracer.userData.life<=0)tracer.visible=false}
 for(let i=groundLasers.length-1;i>=0;i--){const laser=groundLasers[i];laser.age+=dt;if(laser.age>=0)laser.mesh.visible=true;if(!laser.active&&laser.age>=1.05){laser.active=true;laser.mesh.material=laserActiveMaterial;laser.mesh.scale.set(laser.vertical?2.4:1,1,laser.vertical?1:2.4)}if(laser.active){const progress=Math.min(1,(laser.age-1.05)/6.8);laser.lane=THREE.MathUtils.lerp(laser.start,laser.end,progress);if(laser.vertical)laser.mesh.position.x=laser.lane;else laser.mesh.position.z=laser.lane;if(!laser.hit&&laserDamageCooldown<=0&&camera.position.y<PLAYER_HEIGHT+.82&&Math.abs((laser.vertical?camera.position.x:camera.position.z)-laser.lane)<.72){laser.hit=true;laserDamageCooldown=1;if(!playerHit())break}}if(laser.age>=7.85){scene.remove(laser.mesh);groundLasers.splice(i,1)}}
 for(let i=bossOrbs.length-1;i>=0;i--){const orb=bossOrbs[i];orb.mesh.rotation.x+=dt*5;orb.mesh.rotation.y+=dt*7;if(!orb.launched){if(!enemies.includes(orb.boss)){scene.remove(orb.mesh);bossOrbs.splice(i,1);continue}orb.boss.core.getWorldPosition(tmpBossCore);orb.angle+=dt*.8;orb.mesh.position.set(tmpBossCore.x+Math.cos(orb.angle)*1.18,tmpBossCore.y+Math.sin(orb.angle)*1.05,tmpBossCore.z+Math.sin(orb.angle*2)*.3);continue}orb.life-=dt;orb.velocity.applyAxisAngle(upAxis,orb.curve*dt);orb.mesh.position.addScaledVector(orb.velocity,dt);if(orb.life<=0||blocked(orb.mesh.position.x,orb.mesh.position.z,.24)){scene.remove(orb.mesh);bossOrbs.splice(i,1);continue}if(orb.mesh.position.distanceToSquared(camera.position)<.55){scene.remove(orb.mesh);bossOrbs.splice(i,1);if(!playerHit())break}}
 for(let i=allies.length-1;i>=0;i--){const ally=allies[i];ally.cooldown-=dt;if(!enemies.length)continue;let target=enemies[0],best=Infinity;for(const e of enemies){const d=ally.mesh.position.distanceToSquared(e.mesh.position);if(d<best){best=d;target=e}}ally.mesh.lookAt(target.mesh.position.x,ally.mesh.position.y,target.mesh.position.z);if(ally.cooldown<=0){ally.cooldown=2*GAME_SPEED;const start=new THREE.Vector3(ally.mesh.position.x,1.55,ally.mesh.position.z),end=new THREE.Vector3(target.mesh.position.x,1.35,target.mesh.position.z);spawnTracerBetween(start,end,0x72ff4f);damageEnemy(target,1);ally.shots--;if(ally.shots<=0){scene.remove(ally.mesh);allies.splice(i,1);flash('CACTUS ESGOTADO  //  50 TIROS')}}}
 const enemyTime=dt*(buffs.freeze>0 ? .38 : 1);for(let i=0;i<enemies.length;i++){const e=enemies[i],p=e.mesh.position;const vx=camera.position.x-p.x,vz=camera.position.z-p.z,dist=Math.hypot(vx,vz);if(e.mixer)e.mixer.update(enemyTime);else if(e.visual){e.step+=enemyTime*6;e.visual.position.y=e.visualBaseY+Math.abs(Math.sin(e.step))*.045;e.visual.rotation.z=Math.sin(e.step)*.035;e.visual.rotation.x=.06+Math.cos(e.step)*.025}e.mesh.lookAt(camera.position.x,p.y,camera.position.z);if(e.isBoss){if(e.laserBoss)updateLaserBoss(e,enemyTime);else if(e.charging){e.chargeTimer+=enemyTime;e.coreBall.scale.setScalar(1+e.chargeTimer*.42);e.coreBall.material.opacity=.6+.35*Math.sin(t*.025);if(e.chargeTimer>=2.25)spawnBossOrbs(e)}else if(e.volleyActive){e.volleyTimer-=enemyTime;if(e.volleyTimer<=0){const orb=bossOrbs.find(o=>o.boss===e&&!o.launched);if(orb){launchBossOrb(orb);e.volleyTimer=.3;const waiting=bossOrbs.filter(o=>o.boss===e&&!o.launched).length;flash(`ORBE DISPARADO  //  ${waiting} AGUARDANDO`);if(waiting===0){e.volleyActive=false;e.attackCooldown=Math.max(4.8,8.5-(wave/10)*.35)}}else{e.volleyActive=false;e.attackCooldown=Math.max(4.8,8.5-(wave/10)*.35)}}}else{e.attackCooldown-=enemyTime;if(e.attackCooldown<=0){e.charging=true;e.chargeTimer=0;e.core.visible=true;e.coreBall.scale.setScalar(1);flash('GARGANTUAR CARREGANDO  //  PREPARE-SE!')}}}let nx=p.x+vx/dist*e.speed*enemyTime,nz=p.z+vz/dist*e.speed*enemyTime;const radius=e.isBoss?1.15:.55;if(!blocked(nx,p.z,radius))p.x=nx;if(!blocked(p.x,nz,radius))p.z=nz;for(let j=i+1;j<enemies.length;j++){const q=enemies[j].mesh.position,ax=p.x-q.x,az=p.z-q.z,ad=Math.hypot(ax,az);if(ad<1.15&&ad>.001){const push=(1.15-ad)*.5;p.x+=ax/ad*push;q.x-=ax/ad*push;p.z+=az/ad*push;q.z-=az/ad*push}}if(dist<(e.isBoss?1.65:1.02)&&camera.position.y<2.25){if(playerHit(e)){if(!e.isBoss)i--}else break}}
 E.textContent=enemies.length}
function drawMinimap(){const c=minimapCtx,size=180,pad=8,scale=(size-pad*2)/80,toX=x=>pad+(x+40)*scale,toY=z=>pad+(z+40)*scale;c.clearRect(0,0,size,size);c.fillStyle='#031017';c.fillRect(0,0,size,size);c.strokeStyle='#0c3340';c.lineWidth=1;for(let n=-30;n<=30;n+=10){c.beginPath();c.moveTo(toX(n),pad);c.lineTo(toX(n),size-pad);c.moveTo(pad,toY(n));c.lineTo(size-pad,toY(n));c.stroke()}c.fillStyle='#52636a';for(const wall of walls)c.fillRect(toX(wall.x-wall.w/2),toY(wall.z-wall.d/2),Math.max(2,wall.w*scale),Math.max(2,wall.d*scale));for(const enemy of enemies){c.fillStyle=enemy.isBoss?'#ffb13b':'#ff345c';c.shadowColor=c.fillStyle;c.shadowBlur=enemy.isBoss?9:5;c.beginPath();c.arc(toX(enemy.mesh.position.x),toY(enemy.mesh.position.z),enemy.isBoss?5:2.7,0,Math.PI*2);c.fill()}c.shadowBlur=0;c.save();c.translate(toX(camera.position.x),toY(camera.position.z));c.rotate(-yaw);c.fillStyle='#51f5ff';c.shadowColor='#00dcea';c.shadowBlur=10;c.beginPath();c.moveTo(0,-7);c.lineTo(5,6);c.lineTo(0,3);c.lineTo(-5,6);c.closePath();c.fill();c.restore();c.strokeStyle='#00dcea88';c.strokeRect(pad,pad,size-pad*2,size-pad*2)}
function loop(t){requestAnimationFrame(loop);const dt=Math.min((t-last)/1000,.05),speed=GAME_SPEED*gameSpeedMultiplier;last=t;if(active&&!paused)update(dt*speed,t*speed);drawMinimap();renderer.render(scene,camera)}requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
